// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DodawaniewycieczkiTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dodawaniewycieczki() {
    driver.get("http://localhost:4200//manageTrips");
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    driver.findElement(By.cssSelector(".goodButton > .mat-button-wrapper")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    driver.findElement(By.xpath("//mat-select[@id=\'groupSelect\']/div/div/span")).click();
    driver.findElement(By.cssSelector("#Tatry\\ i\\ Podtatrze > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".ng-trigger > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-select-placeholder")).click();
    driver.findElement(By.cssSelector("#Tatry\\ Wysokie > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon > path")).click();
    driver.findElement(By.cssSelector(".mat-calendar-body-today")).click();
    driver.findElement(By.cssSelector("#mat-checkbox-1 .mat-checkbox-inner-container")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id=\'mat-dialog-0\']/app-add-route-dialog/div[3]/button[2]/span")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    vars.put("currentDate", js.executeScript("var d= new Date(); var m=((d.getMonth()+1)<10)?\'0\'+(d.getMonth()+1):(d.getMonth()+1); return d.getFullYear()+\"-\"+m+\"-\"+d.getDate();"));
    {
      String value = driver.findElement(By.id("mat-input-0")).getAttribute("value");
      assertThat(value, is("vars.get("currentDate").toString()"));
    }
    {
      String value = driver.findElement(By.id("mat-input-1")).getAttribute("value");
      assertThat(value, is("vars.get("currentDate").toString()"));
    }
    {
      String value = driver.findElement(By.id("mat-input-4")).getAttribute("value");
      assertThat(value, is("Tatry i Podtatrze"));
    }
    assertThat(driver.findElement(By.cssSelector(".ng-tns-c17-5:nth-child(3) > .ng-tns-c17-5:nth-child(1)")).getText(), is("Suma punktów: 5"));
    driver.findElement(By.xpath("//span[contains(.,\'Dodaj trasę add\')]")).click();
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon > path")).click();
    driver.findElement(By.cssSelector(".mat-calendar-body-today")).click();
    driver.findElement(By.cssSelector("#mat-checkbox-6 .mat-checkbox-inner-container")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id=\'mat-dialog-1\']/app-add-route-dialog/div[2]/button[2]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    assertThat(driver.findElement(By.cssSelector(".ng-tns-c17-5:nth-child(3) > .ng-tns-c17-5:nth-child(1)")).getText(), is("Suma punktów: 11"));
    driver.findElement(By.cssSelector(".ng-trigger > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon > path")).click();
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(7) > .mat-calendar-body-cell-content")).click();
    driver.findElement(By.cssSelector(".mat-checkbox-inner-container")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id=\'mat-dialog-2\']/app-add-route-dialog/div[2]/button[2]/span")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    assertThat(driver.findElement(By.cssSelector(".ng-tns-c17-5:nth-child(3) > .ng-tns-c17-5:nth-child(1)")).getText(), is("Suma punktów: 15"));
    driver.findElement(By.cssSelector(".ng-trigger > .mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon > path")).click();
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(7) > .mat-calendar-body-cell-content")).click();
    driver.findElement(By.cssSelector("#mat-checkbox-9 .mat-checkbox-inner-container")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id=\'mat-dialog-3\']/app-add-route-dialog/div[2]/button[2]/span")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    assertThat(driver.findElement(By.cssSelector(".ng-tns-c17-5:nth-child(3) > .ng-tns-c17-5:nth-child(1)")).getText(), is("Suma punktów: 15"));
    driver.findElement(By.xpath("//button[contains(.,\'Zatwierdź check\')]")).click();
    driver.findElement(By.xpath("//span[contains(.,\'OK\')]")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      WebElement element = driver.findElement(By.cssSelector(".mat-progress-spinner"));
      wait.until(ExpectedConditions.stalenessOf(element));
    }
    assertThat(driver.findElement(By.cssSelector(".mat-row:nth-child(5) > .cdk-column-beginDate")).getText(), is("vars.get(\"currentDate\").toString()"));
    assertThat(driver.findElement(By.cssSelector(".mat-row:nth-child(5) > .cdk-column-endDate")).getText(), is("vars.get(\"currentDate\").toString()"));
    assertThat(driver.findElement(By.cssSelector(".mat-row:nth-child(5) > .cdk-column-mntGroups")).getText(), is("Tatry i Podtatrze"));
    assertThat(driver.findElement(By.cssSelector(".mat-row:nth-child(5) > .cdk-column-score")).getText(), is("15"));
  }
}
